name: Deploy Frontend

on:
    workflow_call:
      inputs:
        github_ref:
          required: true
          type: string
        vite_api_url:
          required: true
          type: string
        vite_ws_url:
          required: true
          type: string
        public_ssh_key:
          required: true
          type: string
        public_server_ip:
          required: true
          type: string
        deploy_user:
          required: true
          type: string
        deploy_path:
          required: true
          type: string
jobs:
    build-frontend:
        runs-on: ubuntu-latest
        name: Build Frontend
        environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'staging' }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'node'

            - name: Install dependencies
              run: npm install -g pnpm && pnpm install --no-frozen-lockfile

            - name: Build
              env:
                VITE_API_URL : ${{inputs.vite_api_url}}
                VITE_WS_URL : ${{inputs.vite_ws_url}}
              run: cd apps/frontend && pnpm build

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: frontend-build
                  path: apps/frontend/dist

    deploy-frontend:
        needs: build-frontend
        runs-on: ubuntu-latest
        name: Deploy Frontend
        environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'staging' }}
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                  name: frontend-build
                  path: apps/frontend/dist

            - name: Set up SSH Key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ inputs.public_ssh_key }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -t rsa ${{ inputs.public_server_ip }} >> ~/.ssh/known_hosts

            - name: Deploy to Nginx
              run: |
                  PUBLIC_SERVER_IP=${{ inputs.public_server_ip }}
                  DEPLOY_USER=${{ inputs.deploy_user }}
                  DEPLOY_PATH=${{ inputs.deploy_path }}

                  scp -i ~/.ssh/id_rsa -r apps/frontend/dist/* $DEPLOY_USER@$PUBLIC_SERVER_IP:$DEPLOY_PATH
                  ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$PUBLIC_SERVER_IP "chmod -R 700 $DEPLOY_PATH"
