name: Test PR

on:
    pull_request:
        branches: [develop, main]

jobs:
    test:
        runs-on: ubuntu-latest
        name: Set up Node environment

        strategy:
            matrix:
                app: [frontend, backend]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'node'

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install root dependencies
              run: pnpm install --no-frozen-lockfile

            - name: Build ${{ matrix.app }}
              working-directory: apps/${{ matrix.app }}
              run: pnpm run build

            - name: Run tests for ${{ matrix.app }}
              working-directory: apps/${{ matrix.app }}
              run: pnpm test

    deploy-trigger:
      needs: test
      runs-on: ubuntu-latest

      if: github.ref == 'refs/heads/develop'

      strategy:
        matrix:
          app: [frontend, backend]

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Check for changes
          id: check-changes
          run: |
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
            if grep -q "^apps/${{ matrix.app }}" changed_files.txt; then
                echo "changed=true" >> $GITHUB_ENV
            else
                echo "changed=false" >> $GITHUB_ENV

        - name: Trigger deploy-frontend
          if: env.changed == 'true' && matrix.app == 'frontend'
          uses: .github/workflows/deploy-frontend.yml

        - name: Trigger deploy-backend
          if: env.changed == 'true' && matrix.app == 'backend'
          uses: .github/workflows/deploy-backend.yml

